// Generated by CoffeeScript 1.4.0
(function() {
  var Adapter, EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  EventEmitter = require('events').EventEmitter;

  Adapter = (function(_super) {

    __extends(Adapter, _super);

    function Adapter(robot) {
      this.robot = robot;
    }

    Adapter.prototype.send = function() {
      var envelope, strings;
      envelope = arguments[0], strings = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    };

    Adapter.prototype.reply = function() {
      var envelope, strings;
      envelope = arguments[0], strings = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    };

    Adapter.prototype.topic = function() {
      var envelope, strings;
      envelope = arguments[0], strings = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    };

    Adapter.prototype.run = function() {};

    Adapter.prototype.close = function() {};

    Adapter.prototype.receive = function(message) {
      return this.robot.receive(message);
    };

    Adapter.prototype.users = function() {
      return this.robot.brain.users();
    };

    Adapter.prototype.userForId = function(id, options) {
      return this.robot.brain.userForId(id, options);
    };

    Adapter.prototype.userForName = function(name) {
      return this.robot.brain.userForName(name);
    };

    Adapter.prototype.usersForRawFuzzyName = function(fuzzyName) {
      return this.robot.brain.usersForRawFuzzyName(fuzzyName);
    };

    Adapter.prototype.usersForFuzzyName = function(fuzzyName) {
      return this.robot.brain.usersForFuzzyName(fuzzyName);
    };

    Adapter.prototype.http = function(url) {
      return this.robot.http(url);
    };

    return Adapter;

  })(EventEmitter);

  module.exports = Adapter;

}).call(this);
