// Generated by CoffeeScript 1.4.0
(function() {
  var Listener, TextListener, TextMessage,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TextMessage = require('./message').TextMessage;

  Listener = (function() {

    function Listener(robot, matcher, callback) {
      this.robot = robot;
      this.matcher = matcher;
      this.callback = callback;
    }

    Listener.prototype.call = function(message) {
      var match;
      if (match = this.matcher(message)) {
        this.callback(new this.robot.Response(this.robot, message, match));
        return true;
      } else {
        return false;
      }
    };

    return Listener;

  })();

  TextListener = (function(_super) {

    __extends(TextListener, _super);

    function TextListener(robot, regex, callback) {
      var _this = this;
      this.robot = robot;
      this.regex = regex;
      this.callback = callback;
      this.matcher = function(message) {
        if (message instanceof TextMessage) {
          return message.match(_this.regex);
        }
      };
    }

    return TextListener;

  })(Listener);

  module.exports = {
    Listener: Listener,
    TextListener: TextListener
  };

}).call(this);
